// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReludeReact = require("../../src/ReludeReact.bs.js");

function handleClick(_event) {
  console.log("clicked!");
  return /* () */0;
}

function Component1(Props) {
  var message = Props.message;
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, ReludeReact.title), React.createElement("div", {
                  onClick: handleClick
                }, message));
}

var make = Component1;

exports.handleClick = handleClick;
exports.make = make;
/* react Not a pure module */
